homeassistant:
  # Name of the location where Home Assistant is running
  name: Knottebo
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 96
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

system_health:

person:

# Enables the frontend
frontend: !include frontend.yaml

# Lovelace
#lovelace:
#  mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret duckdns_base
  trusted_networks:
    - !secret trusted_1
    - !secret trusted_2
  ip_ban_enabled: true
  login_attempts_threshold: 5

# iFrame panel
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret duckdns_port

# Mitsubishi värmepump
climate:
  - platform: melcloud
    email: !secret melcloud_email
    password: !secret melcloud_password
    
# rfxtrx
rfxtrx:
  device: /dev/ttyUSB0

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Discover some devices automatically
discovery:

# Database settings
recorder:
  include:
    domains:
      - switch
      - sensor
      - media_player

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
      - sensor
      - media_player

# View all events in a logbook
logbook:
logger:
  default: warning

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather
weather:
#  - platform: darksky
#    api_key: !secret dark_sky_api
  - platform: smhi

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Telldus
tellduslive:

# Verisure
verisure:
  username: !secret verisure_user
  password: !secret verisure_pass

# Melissa värmepump
melissa:
  username: !secret melissa_user
  password: !secret melissa_pass

# nmap
#device_tracker:
#  - platform: nmap_tracker
#    track_new_devices: no
#    consider_home: 180
#    hosts: *

ios:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Apple TV
apple_tv: !include apple_tv.yaml
# Switches
switch: !include_dir_list switches/
# Sensors
sensor: !include_dir_list sensors/
# Binary sensors
binary_sensor: !include_dir_list binary_sensors/
# Cameras
camera: !include cameras.yaml
